version: "3.7"

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    links:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./drkiq
        target: /opt/app/drkiq
    ports:
      - '8010:8010'
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      SECRET_TOKEN: "Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw"
      WORKER_PROCESSES: 1
      LISTEN_ON: "0.0.0.0:8010"
      DATABASE_URL: "postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000"
      CACHE_URL: "redis://redis:6379/0"
      JOB_WORKER_URL: "redis://redis:6379/0"

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./drkiq
        target: /opt/app/drkiq
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      SECRET_TOKEN: "Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw"
      WORKER_PROCESSES: 1
      LISTEN_ON: "0.0.0.0:8010"
      DATABASE_URL: "postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000"
      CACHE_URL: "redis://redis:6379/0"
      JOB_WORKER_URL: "redis://redis:6379/0"

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - drkiq
    ports:
      - '8020:8020'

volumes:
  drkiq-postgres:
  drkiq-redis:
