version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    image: $DOCKER_USERNAME/drkiq:latest
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    environment:
      SECRET_TOKEN: "Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw"
      WORKER_PROCESSES: 1
      LISTEN_ON: "0.0.0.0:8010"
      DATABASE_URL: "postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000"
      CACHE_URL: "redis://redis:6379/0"
      JOB_WORKER_URL: "redis://redis:6379/0"

  sidekiq:
    image: $DOCKER_USERNAME/drkiq:latest
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    environment:
      SECRET_TOKEN: "Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw"
      WORKER_PROCESSES: 1
      LISTEN_ON: "0.0.0.0:8010"
      DATABASE_URL: "postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000"
      CACHE_URL: "redis://redis:6379/0"
      JOB_WORKER_URL: "redis://redis:6379/0"

  nginx:
    image: $DOCKER_USERNAME/dockerizing-ruby_nginx:latest
    links:
      - drkiq
    ports:
      - '8020:8020'

volumes:
  drkiq-postgres:
  drkiq-redis:
